### ISSUE TITLE
Add combined build.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-installer#164]
See https://github.com/silverstripe/silverstripe-framework/issues/6758 for context.

## Acceptance criteria

On the master branch...

 * silverstripe/installer has a travis run that executes all PHPUnit & Behat tests from all modules within it
 * Only PHP 5.6 + MySQL and PHP 5.6 + PostgreSQL need be run: the full gamut of combinations can be left to the individual module builds.
 * This build is triggered to run daily, unless it has otherwise been run in the last day (travis now has this feature)

Once this is done, the CMS tests in framework can be removed.

## Tasks

 - [x] At least one PGSQL build
 - [x] Add framework behat tests to installer
 - [x] Add cms behat tests to installer
 - [x] Add asset-admin behat tests to installer
 - [x] setup travis artifacts upload to installer
 
## PRs:

 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/484
 - [x] https://github.com/silverstripe/silverstripe-graphql/pull/99
 - [ ] https://github.com/silverstripe/silverstripe-installer/pull/178
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6962
 - [x] https://github.com/silverstripe/silverstripe-graphql/pull/101

**Comment by tractorcow** [comment]
We've added a basic test suite in installer and set on a 24hr cron.

We still need to add in behat tests, as well as the readme badge integration.

**Comment by sminnee** [comment]
Pull request for the behat tests here: https://github.com/silverstripe/silverstripe-installer/pull/176

**Comment by sminnee** [comment]
Shifted to beta1 as it's non trivial ;-)

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-installer/pull/178
